name: Update VPS

on:
  push:
    branches:
      - master

jobs:
  update_vps:
    runs-on: self-hosted

    needs: dockerpush

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update.sh on VPS
        run: |
          ./update.sh
