name: Update VPS

on:
    workflow_run:
      workflows: ["Publish Docker image"]
      branches: [master]
      types:
        - completed
  push:
    branches:
      - master

jobs:
  update_vps:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update.sh on VPS
        run: |
          ./update.sh
