name: Update VPS

on:
  push:
    branches:
      - master
jobs:
  update_vps:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: "Create env file"
        run: |
          echo "${{ secrets.CLIENT_ENV_FILE }}" > ./client/.env
          echo "${{ secrets.SERVER_ENV_FILE }}" > ./server/.env

      - name: Run update.sh on VPS
        run: |
          docker-compose build --no-cache
          docker compose up -d
