name: Update VPS

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
jobs:
  update_vps:
    runs-on: self-hosted

    steps:
      - name: Run update.sh on VPS
        run: |
          ./update.sh
