name: Update VPS

on:
  push:
    branches:
      - master
jobs:
  update_vps:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update.sh on VPS
        run: |
          docker compose up -d
